server:
  port: 3003
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/chat-test
    username: sa
    password: rladlsrnr
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
